spring.application.name=BFF

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- SEGURIDAD AUTH0 ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-dantesakt1.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api-sanosysalvos-auth0/